"""add_blacklistkeyword_filtereditem

Revision ID: 5668bdccb3e7
Revises: ba368bbde8b5
Create Date: 2026-05-24 21:31:21.253692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = '5668bdccb3e7'
down_revision: Union[str, None] = 'ba368bbde8b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklistkeyword',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pattern', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('match_field', sa.Text(), server_default='title', nullable=False),
    sa.Column('is_regex', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), server_default='', nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blacklistkeyword_pattern'), 'blacklistkeyword', ['pattern'], unique=False)
    op.create_table('filtereditem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('filter_reason', sa.Text(), server_default='', nullable=False),
    sa.Column('filter_rule_id', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('board_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['board.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['filter_rule_id'], ['blacklistkeyword.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_filtereditem_board_id'), 'filtereditem', ['board_id'], unique=False)
    op.create_index(op.f('ix_filtereditem_status'), 'filtereditem', ['status'], unique=False)
    op.create_index(op.f('ix_filtereditem_url'), 'filtereditem', ['url'], unique=False)
    # NOTE: Cosmetic ALTER COLUMN / constraint changes stripped (SQLite-incompatible).
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_filtereditem_url'), table_name='filtereditem')
    op.drop_index(op.f('ix_filtereditem_status'), table_name='filtereditem')
    op.drop_index(op.f('ix_filtereditem_board_id'), table_name='filtereditem')
    op.drop_table('filtereditem')
    op.drop_index(op.f('ix_blacklistkeyword_pattern'), table_name='blacklistkeyword')
    op.drop_table('blacklistkeyword')
    # ### end Alembic commands ###
