"""add_source_promptconfig_modelapiconfig_taskrun

Revision ID: ba368bbde8b5
Revises:
Create Date: 2026-05-23 14:01:19.267077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes  # noqa: F401 — needed for AutoString columns


# revision identifiers, used by Alembic.
revision: str = 'ba368bbde8b5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modelapiconfig',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('base_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('api_key', sa.Text(), server_default='', nullable=False),
    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('concurrency', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modelapiconfig_name'), 'modelapiconfig', ['name'], unique=True)
    op.create_table('promptconfig',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('template', sa.Text(), nullable=False),
    sa.Column('system_prompt', sa.Text(), server_default='', nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('model_api_config_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['model_api_config_id'], ['modelapiconfig.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promptconfig_key'), 'promptconfig', ['key'], unique=True)
    op.create_table('source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('site_url', sa.Text(), server_default='', nullable=False),
    sa.Column('source_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('board_id', sa.Integer(), nullable=True),
    sa.Column('health_status', sa.Text(), server_default='healthy', nullable=False),
    sa.Column('last_fetched_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['board.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_board_id'), 'source', ['board_id'], unique=False)
    op.create_index(op.f('ix_source_source_type'), 'source', ['source_type'], unique=False)
    op.create_index(op.f('ix_source_url'), 'source', ['url'], unique=False)
    op.create_table('taskrun',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('trigger_type', sa.Text(), server_default='scheduled', nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('progress_label', sa.Text(), server_default='', nullable=False),
    sa.Column('progress_current', sa.Integer(), nullable=False),
    sa.Column('progress_total', sa.Integer(), nullable=False),
    sa.Column('stage_timings', sa.JSON(), nullable=True),
    sa.Column('ai_call_breakdown', sa.JSON(), nullable=True),
    sa.Column('error_summary', sa.Text(), server_default='', nullable=False),
    sa.Column('board_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['board.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_taskrun_board_id'), 'taskrun', ['board_id'], unique=False)
    op.create_index(op.f('ix_taskrun_kind'), 'taskrun', ['kind'], unique=False)
    op.create_index(op.f('ix_taskrun_status'), 'taskrun', ['status'], unique=False)
    # NOTE: Cosmetic ALTER COLUMN type changes (VARCHAR→JSON/Text, REAL→Float)
    # and constraint re-creation removed — SQLite stores all as TEXT and these
    # are already handled by db.py legacy migrations at startup.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_taskrun_status'), table_name='taskrun')
    op.drop_index(op.f('ix_taskrun_kind'), table_name='taskrun')
    op.drop_index(op.f('ix_taskrun_board_id'), table_name='taskrun')
    op.drop_table('taskrun')
    op.drop_index(op.f('ix_source_url'), table_name='source')
    op.drop_index(op.f('ix_source_source_type'), table_name='source')
    op.drop_index(op.f('ix_source_board_id'), table_name='source')
    op.drop_table('source')
    op.drop_index(op.f('ix_promptconfig_key'), table_name='promptconfig')
    op.drop_table('promptconfig')
    op.drop_index(op.f('ix_modelapiconfig_name'), table_name='modelapiconfig')
    op.drop_table('modelapiconfig')
    # ### end Alembic commands ###
